// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	apps_v1beta1 "k8s.io/api/apps/v1beta1"
	batch_v1 "k8s.io/api/batch/v1"
	v1 "k8s.io/api/core/v1"
	v1alpha1 "k8s.io/api/delegatedadmission/v1alpha1"
	v1beta1 "k8s.io/api/extensions/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	api "k8s.io/kubernetes/pkg/api"
	api_v1 "k8s.io/kubernetes/pkg/api/v1"
	apps "k8s.io/kubernetes/pkg/apis/apps"
	batch "k8s.io/kubernetes/pkg/apis/batch"
	delegatedadmission "k8s.io/kubernetes/pkg/apis/delegatedadmission"
	extensions "k8s.io/kubernetes/pkg/apis/extensions"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_AdmissionReview_To_delegatedadmission_AdmissionReview,
		Convert_delegatedadmission_AdmissionReview_To_v1alpha1_AdmissionReview,
		Convert_v1alpha1_AdmissionReviewList_To_delegatedadmission_AdmissionReviewList,
		Convert_delegatedadmission_AdmissionReviewList_To_v1alpha1_AdmissionReviewList,
		Convert_v1alpha1_AdmissionReviewObject_To_delegatedadmission_AdmissionReviewObject,
		Convert_delegatedadmission_AdmissionReviewObject_To_v1alpha1_AdmissionReviewObject,
		Convert_v1alpha1_AdmissionReviewSpec_To_delegatedadmission_AdmissionReviewSpec,
		Convert_delegatedadmission_AdmissionReviewSpec_To_v1alpha1_AdmissionReviewSpec,
		Convert_v1alpha1_AdmissionReviewStatus_To_delegatedadmission_AdmissionReviewStatus,
		Convert_delegatedadmission_AdmissionReviewStatus_To_v1alpha1_AdmissionReviewStatus,
	)
}

func autoConvert_v1alpha1_AdmissionReview_To_delegatedadmission_AdmissionReview(in *v1alpha1.AdmissionReview, out *delegatedadmission.AdmissionReview, s conversion.Scope) error {
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.ObjectMeta, &out.ObjectMeta, 0); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AdmissionReviewSpec_To_delegatedadmission_AdmissionReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_AdmissionReviewStatus_To_delegatedadmission_AdmissionReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AdmissionReview_To_delegatedadmission_AdmissionReview is an autogenerated conversion function.
func Convert_v1alpha1_AdmissionReview_To_delegatedadmission_AdmissionReview(in *v1alpha1.AdmissionReview, out *delegatedadmission.AdmissionReview, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdmissionReview_To_delegatedadmission_AdmissionReview(in, out, s)
}

func autoConvert_delegatedadmission_AdmissionReview_To_v1alpha1_AdmissionReview(in *delegatedadmission.AdmissionReview, out *v1alpha1.AdmissionReview, s conversion.Scope) error {
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.ObjectMeta, &out.ObjectMeta, 0); err != nil {
		return err
	}
	if err := Convert_delegatedadmission_AdmissionReviewSpec_To_v1alpha1_AdmissionReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_delegatedadmission_AdmissionReviewStatus_To_v1alpha1_AdmissionReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_delegatedadmission_AdmissionReview_To_v1alpha1_AdmissionReview is an autogenerated conversion function.
func Convert_delegatedadmission_AdmissionReview_To_v1alpha1_AdmissionReview(in *delegatedadmission.AdmissionReview, out *v1alpha1.AdmissionReview, s conversion.Scope) error {
	return autoConvert_delegatedadmission_AdmissionReview_To_v1alpha1_AdmissionReview(in, out, s)
}

func autoConvert_v1alpha1_AdmissionReviewList_To_delegatedadmission_AdmissionReviewList(in *v1alpha1.AdmissionReviewList, out *delegatedadmission.AdmissionReviewList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]delegatedadmission.AdmissionReview, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_AdmissionReview_To_delegatedadmission_AdmissionReview(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_AdmissionReviewList_To_delegatedadmission_AdmissionReviewList is an autogenerated conversion function.
func Convert_v1alpha1_AdmissionReviewList_To_delegatedadmission_AdmissionReviewList(in *v1alpha1.AdmissionReviewList, out *delegatedadmission.AdmissionReviewList, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdmissionReviewList_To_delegatedadmission_AdmissionReviewList(in, out, s)
}

func autoConvert_delegatedadmission_AdmissionReviewList_To_v1alpha1_AdmissionReviewList(in *delegatedadmission.AdmissionReviewList, out *v1alpha1.AdmissionReviewList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]v1alpha1.AdmissionReview, len(*in))
		for i := range *in {
			if err := Convert_delegatedadmission_AdmissionReview_To_v1alpha1_AdmissionReview(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_delegatedadmission_AdmissionReviewList_To_v1alpha1_AdmissionReviewList is an autogenerated conversion function.
func Convert_delegatedadmission_AdmissionReviewList_To_v1alpha1_AdmissionReviewList(in *delegatedadmission.AdmissionReviewList, out *v1alpha1.AdmissionReviewList, s conversion.Scope) error {
	return autoConvert_delegatedadmission_AdmissionReviewList_To_v1alpha1_AdmissionReviewList(in, out, s)
}

func autoConvert_v1alpha1_AdmissionReviewObject_To_delegatedadmission_AdmissionReviewObject(in *v1alpha1.AdmissionReviewObject, out *delegatedadmission.AdmissionReviewObject, s conversion.Scope) error {
	out.Namespace = (*api.Namespace)(unsafe.Pointer(in.Namespace))
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(api.Pod)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.Pod = nil
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(batch.Job)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.Job = nil
	}
	if in.ReplicationController != nil {
		in, out := &in.ReplicationController, &out.ReplicationController
		*out = new(api.ReplicationController)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.ReplicationController = nil
	}
	if in.ReplicaSet != nil {
		in, out := &in.ReplicaSet, &out.ReplicaSet
		*out = new(extensions.ReplicaSet)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.ReplicaSet = nil
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(extensions.Deployment)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.Deployment = nil
	}
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(apps.StatefulSet)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.StatefulSet = nil
	}
	if in.DaemonSet != nil {
		in, out := &in.DaemonSet, &out.DaemonSet
		*out = new(extensions.DaemonSet)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.DaemonSet = nil
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(api.Service)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.Service = nil
	}
	out.Ingress = (*extensions.Ingress)(unsafe.Pointer(in.Ingress))
	return nil
}

// Convert_v1alpha1_AdmissionReviewObject_To_delegatedadmission_AdmissionReviewObject is an autogenerated conversion function.
func Convert_v1alpha1_AdmissionReviewObject_To_delegatedadmission_AdmissionReviewObject(in *v1alpha1.AdmissionReviewObject, out *delegatedadmission.AdmissionReviewObject, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdmissionReviewObject_To_delegatedadmission_AdmissionReviewObject(in, out, s)
}

func autoConvert_delegatedadmission_AdmissionReviewObject_To_v1alpha1_AdmissionReviewObject(in *delegatedadmission.AdmissionReviewObject, out *v1alpha1.AdmissionReviewObject, s conversion.Scope) error {
	out.Namespace = (*v1.Namespace)(unsafe.Pointer(in.Namespace))
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(v1.Pod)
		if err := api_v1.Convert_api_Pod_To_v1_Pod(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Pod = nil
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(batch_v1.Job)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.Job = nil
	}
	if in.ReplicationController != nil {
		in, out := &in.ReplicationController, &out.ReplicationController
		*out = new(v1.ReplicationController)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.ReplicationController = nil
	}
	if in.ReplicaSet != nil {
		in, out := &in.ReplicaSet, &out.ReplicaSet
		*out = new(v1beta1.ReplicaSet)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.ReplicaSet = nil
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1beta1.Deployment)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.Deployment = nil
	}
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		*out = new(apps_v1beta1.StatefulSet)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.StatefulSet = nil
	}
	if in.DaemonSet != nil {
		in, out := &in.DaemonSet, &out.DaemonSet
		*out = new(v1beta1.DaemonSet)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.DaemonSet = nil
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(v1.Service)
		// TODO: Inefficient conversion - can we improve it?
		if err := s.Convert(*in, *out, 0); err != nil {
			return err
		}
	} else {
		out.Service = nil
	}
	out.Ingress = (*v1beta1.Ingress)(unsafe.Pointer(in.Ingress))
	return nil
}

// Convert_delegatedadmission_AdmissionReviewObject_To_v1alpha1_AdmissionReviewObject is an autogenerated conversion function.
func Convert_delegatedadmission_AdmissionReviewObject_To_v1alpha1_AdmissionReviewObject(in *delegatedadmission.AdmissionReviewObject, out *v1alpha1.AdmissionReviewObject, s conversion.Scope) error {
	return autoConvert_delegatedadmission_AdmissionReviewObject_To_v1alpha1_AdmissionReviewObject(in, out, s)
}

func autoConvert_v1alpha1_AdmissionReviewSpec_To_delegatedadmission_AdmissionReviewSpec(in *v1alpha1.AdmissionReviewSpec, out *delegatedadmission.AdmissionReviewSpec, s conversion.Scope) error {
	out.User = in.User
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]delegatedadmission.ExtraValue)(unsafe.Pointer(&in.Extra))
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Operation = delegatedadmission.Operation(in.Operation)
	out.Kind = in.Kind
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(delegatedadmission.AdmissionReviewObject)
		if err := Convert_v1alpha1_AdmissionReviewObject_To_delegatedadmission_AdmissionReviewObject(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Object = nil
	}
	if in.OldObject != nil {
		in, out := &in.OldObject, &out.OldObject
		*out = new(delegatedadmission.AdmissionReviewObject)
		if err := Convert_v1alpha1_AdmissionReviewObject_To_delegatedadmission_AdmissionReviewObject(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OldObject = nil
	}
	return nil
}

// Convert_v1alpha1_AdmissionReviewSpec_To_delegatedadmission_AdmissionReviewSpec is an autogenerated conversion function.
func Convert_v1alpha1_AdmissionReviewSpec_To_delegatedadmission_AdmissionReviewSpec(in *v1alpha1.AdmissionReviewSpec, out *delegatedadmission.AdmissionReviewSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdmissionReviewSpec_To_delegatedadmission_AdmissionReviewSpec(in, out, s)
}

func autoConvert_delegatedadmission_AdmissionReviewSpec_To_v1alpha1_AdmissionReviewSpec(in *delegatedadmission.AdmissionReviewSpec, out *v1alpha1.AdmissionReviewSpec, s conversion.Scope) error {
	out.User = in.User
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]v1alpha1.ExtraValue)(unsafe.Pointer(&in.Extra))
	out.Operation = v1alpha1.Operation(in.Operation)
	out.Namespace = in.Namespace
	out.Name = in.Name
	out.Kind = in.Kind
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = new(v1alpha1.AdmissionReviewObject)
		if err := Convert_delegatedadmission_AdmissionReviewObject_To_v1alpha1_AdmissionReviewObject(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Object = nil
	}
	if in.OldObject != nil {
		in, out := &in.OldObject, &out.OldObject
		*out = new(v1alpha1.AdmissionReviewObject)
		if err := Convert_delegatedadmission_AdmissionReviewObject_To_v1alpha1_AdmissionReviewObject(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OldObject = nil
	}
	return nil
}

// Convert_delegatedadmission_AdmissionReviewSpec_To_v1alpha1_AdmissionReviewSpec is an autogenerated conversion function.
func Convert_delegatedadmission_AdmissionReviewSpec_To_v1alpha1_AdmissionReviewSpec(in *delegatedadmission.AdmissionReviewSpec, out *v1alpha1.AdmissionReviewSpec, s conversion.Scope) error {
	return autoConvert_delegatedadmission_AdmissionReviewSpec_To_v1alpha1_AdmissionReviewSpec(in, out, s)
}

func autoConvert_v1alpha1_AdmissionReviewStatus_To_delegatedadmission_AdmissionReviewStatus(in *v1alpha1.AdmissionReviewStatus, out *delegatedadmission.AdmissionReviewStatus, s conversion.Scope) error {
	out.Allowed = in.Allowed
	out.Mutated = in.Mutated
	out.Reason = in.Reason
	out.EvaluationError = in.EvaluationError
	return nil
}

// Convert_v1alpha1_AdmissionReviewStatus_To_delegatedadmission_AdmissionReviewStatus is an autogenerated conversion function.
func Convert_v1alpha1_AdmissionReviewStatus_To_delegatedadmission_AdmissionReviewStatus(in *v1alpha1.AdmissionReviewStatus, out *delegatedadmission.AdmissionReviewStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdmissionReviewStatus_To_delegatedadmission_AdmissionReviewStatus(in, out, s)
}

func autoConvert_delegatedadmission_AdmissionReviewStatus_To_v1alpha1_AdmissionReviewStatus(in *delegatedadmission.AdmissionReviewStatus, out *v1alpha1.AdmissionReviewStatus, s conversion.Scope) error {
	out.Allowed = in.Allowed
	out.Mutated = in.Mutated
	out.Reason = in.Reason
	out.EvaluationError = in.EvaluationError
	return nil
}

// Convert_delegatedadmission_AdmissionReviewStatus_To_v1alpha1_AdmissionReviewStatus is an autogenerated conversion function.
func Convert_delegatedadmission_AdmissionReviewStatus_To_v1alpha1_AdmissionReviewStatus(in *delegatedadmission.AdmissionReviewStatus, out *v1alpha1.AdmissionReviewStatus, s conversion.Scope) error {
	return autoConvert_delegatedadmission_AdmissionReviewStatus_To_v1alpha1_AdmissionReviewStatus(in, out, s)
}
