// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package delegatedadmission

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	api "k8s.io/kubernetes/pkg/api"
	apps "k8s.io/kubernetes/pkg/apis/apps"
	batch "k8s.io/kubernetes/pkg/apis/batch"
	extensions "k8s.io/kubernetes/pkg/apis/extensions"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AdmissionReview).DeepCopyInto(out.(*AdmissionReview))
			return nil
		}, InType: reflect.TypeOf(&AdmissionReview{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AdmissionReviewList).DeepCopyInto(out.(*AdmissionReviewList))
			return nil
		}, InType: reflect.TypeOf(&AdmissionReviewList{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AdmissionReviewObject).DeepCopyInto(out.(*AdmissionReviewObject))
			return nil
		}, InType: reflect.TypeOf(&AdmissionReviewObject{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AdmissionReviewSpec).DeepCopyInto(out.(*AdmissionReviewSpec))
			return nil
		}, InType: reflect.TypeOf(&AdmissionReviewSpec{})},
		conversion.GeneratedDeepCopyFunc{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*AdmissionReviewStatus).DeepCopyInto(out.(*AdmissionReviewStatus))
			return nil
		}, InType: reflect.TypeOf(&AdmissionReviewStatus{})},
	)
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionReview) DeepCopyInto(out *AdmissionReview) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionReview.
func (in *AdmissionReview) DeepCopy() *AdmissionReview {
	if in == nil {
		return nil
	}
	out := new(AdmissionReview)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdmissionReview) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionReviewList) DeepCopyInto(out *AdmissionReviewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdmissionReview, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionReviewList.
func (in *AdmissionReviewList) DeepCopy() *AdmissionReviewList {
	if in == nil {
		return nil
	}
	out := new(AdmissionReviewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdmissionReviewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionReviewObject) DeepCopyInto(out *AdmissionReviewObject) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		if *in == nil {
			*out = nil
		} else {
			*out = new(api.Namespace)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		if *in == nil {
			*out = nil
		} else {
			*out = new(api.Pod)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		if *in == nil {
			*out = nil
		} else {
			*out = new(batch.Job)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.ReplicationController != nil {
		in, out := &in.ReplicationController, &out.ReplicationController
		if *in == nil {
			*out = nil
		} else {
			*out = new(api.ReplicationController)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.ReplicaSet != nil {
		in, out := &in.ReplicaSet, &out.ReplicaSet
		if *in == nil {
			*out = nil
		} else {
			*out = new(extensions.ReplicaSet)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		if *in == nil {
			*out = nil
		} else {
			*out = new(extensions.Deployment)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.StatefulSet != nil {
		in, out := &in.StatefulSet, &out.StatefulSet
		if *in == nil {
			*out = nil
		} else {
			*out = new(apps.StatefulSet)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.DaemonSet != nil {
		in, out := &in.DaemonSet, &out.DaemonSet
		if *in == nil {
			*out = nil
		} else {
			*out = new(extensions.DaemonSet)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		if *in == nil {
			*out = nil
		} else {
			*out = new(api.Service)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		if *in == nil {
			*out = nil
		} else {
			*out = new(extensions.Ingress)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionReviewObject.
func (in *AdmissionReviewObject) DeepCopy() *AdmissionReviewObject {
	if in == nil {
		return nil
	}
	out := new(AdmissionReviewObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionReviewSpec) DeepCopyInto(out *AdmissionReviewSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string]ExtraValue, len(*in))
		for key, val := range *in {
			(*out)[key] = make(ExtraValue, len(val))
			copy((*out)[key], val)
		}
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		if *in == nil {
			*out = nil
		} else {
			*out = new(AdmissionReviewObject)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.OldObject != nil {
		in, out := &in.OldObject, &out.OldObject
		if *in == nil {
			*out = nil
		} else {
			*out = new(AdmissionReviewObject)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionReviewSpec.
func (in *AdmissionReviewSpec) DeepCopy() *AdmissionReviewSpec {
	if in == nil {
		return nil
	}
	out := new(AdmissionReviewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionReviewStatus) DeepCopyInto(out *AdmissionReviewStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionReviewStatus.
func (in *AdmissionReviewStatus) DeepCopy() *AdmissionReviewStatus {
	if in == nil {
		return nil
	}
	out := new(AdmissionReviewStatus)
	in.DeepCopyInto(out)
	return out
}
